namespace: /yourname

app:
    defines: runnable
    version: 0.0.1
    containers:
        defines: containers
        app:
            image: yourname/tutorial:latest
            ports:
                - <- `${port}:${port}`
            environment:
                - <- `PORT=${port}`
                - <- `DB_HOST=${db-host}`
                - <- `DB_PORT=${db-port}`
    variables:
        defines: variables
        port:
            type: int
            value: 8000
        db-host:
            type: string
            value: localhost
        db-port:
            type: int
            value: 27017